name: 'Lab42 helm/kubectl'
description: |
  This action allows to run helm and kubectl commands with a custom helm repo. 
branding:
  icon: 'compass'
  color: 'blue'
inputs:
  helm:
    description: 'The helm command to run (excluding helm)'
    required: true
  kubectl:
    description: 'The kubectl command to run (excluding kubectl)'
    required: true
  repository:
    description: 'The Helm repository will be automatically configured if present. Example: "test https:domain.tld/chart"'
    required: false
  kubeconfig:
    description: 'The contents of this input will be appended to ~/.kube/config'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/lab42/helm:latest'
